export const TYPE_MARKERS = {
  REACTIVE_QUERY: 'REACTIVE_QUERY',
  REACTIVE_MUTATION: 'REACTIVE_MUTATION',
  REACTIVE_SYNC: 'REACTIVE_SYNC',
  REACTIVE_ASYNC: 'REACTIVE_ASYNC',
  REACTIVE_EAGER_ASYNC: 'REACTIVE_EAGER_ASYNC',
  IDIOMATIC_QUERY: 'IDIOMATIC_QUERY',
  IDIOMATIC_MUTATION: 'IDIOMATIC_MUTATION',
  IDIOMATIC_SYNC: 'IDIOMATIC_SYNC',
  IDIOMATIC_ASYNC: 'IDIOMATIC_ASYNC',
  IDIOMATIC_EAGER_ASYNC: 'IDIOMATIC_EAGER_ASYNC',
} as const;

export type TypeMarker = (typeof TYPE_MARKERS)[keyof typeof TYPE_MARKERS];
